//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceRecognition.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistanceResult
    {
        public System.Guid DistanceResultId { get; set; }
        public System.Guid EmployeId { get; set; }
        public int Distance { get; set; }
    
        public virtual Employe Employe { get; set; }
    }
}
